### ISSUE TITLE
Named Graph and SPARUL

### ISSUE THREAD

**Issue by johnss** [semsol/arc2#103]
Does this this library support Named graph SPARQL 1.1 Update
?

https://en.m.wikipedia.org/wiki/SPARUL

**Comment by johnss** [comment]
https://github.com/semsol/arc2/pull/102 doesn't mention anything about named graph
https://en.m.wikipedia.org/wiki/Named_graph

**Comment by bnowack** [comment]
Does https://github.com/semsol/arc2/wiki/SPARQL- help?

ARC2 does not distinguish graphs from named graphs, and the syntax may be out of date, but it is possible to add triples to URi-identified graphs.

**Comment by k00ni** [comment]
Hi, ARC2 uses a SPARQL syntax which is similar to SPARUL. More information about that in the [wiki](https://github.com/semsol/arc2/wiki/SPARQL-).

I am the maintainer of Saft, which integrates ARC2. It transforms SPARUL queries such as:

```sparql
DELETE WHERE {
    Graph <http://localhost/Saft/TestGraph/> {
        ?s ?p ?o .
    }
}
```

to queries which ARC2 understands, like:

```sparql
DELETE FROM <http://localhost/Saft/TestGraph/> {
    ?s ?p ?o .
}
WHERE {
    ?s ?p ?o .
}
```
Maybe it helps.

**Comment by johnss** [comment]
@bnowack I know it can extend triple but will become 4 statement or it will be 5 statement I'm don't know

@k00n1 will it become 5 statement or 4 statement? 

i want the graph to be [(subject -> predicate -> object) -> context]
Not [subject -> predicate -> (subject -> predicate -> object)]

I want to create knowledge base site like wikidata, with improvement, wikidata does not support nesting triple (5 statement) and does not support named graph (4 statement) my site will fix this mediawiki wikibase extension issues so I'm thinking using this lib as a base for data storage.

And probably I will not use sparql and use php method directly to store it in mysql.

**Comment by k00ni** [comment]
Btw. #102 was not about adding new functionality, but to provide a set of tests, checking that a feature is there or missing.

**Comment by johnss** [comment]
@bnowack I know it can extend triple but I'm not sure it will become 4 statement or 5 statement
@k00ni will it become 4 statement or 5 statement

I want the graph to be  (subject-predicate-object)-context

I don't want to become
 subject-predicate-(subject–predicate–object)

**Comment by k00ni** [comment]
Can you paste some example code? I can't follow you, i am afraid.

**Comment by johnss** [comment]
My project is i want to create site like wikidata, I don't have a code example as I will probably use php method directly and not using SPARQL.

My question is how your plug in distinguish between named graph or triples added to URI-
identified graphs?

Triples added to URI-
identified graphs will become 5 node, while true named graph are 4 node, I assume no as Its just a query translator, there's no way to differentiate between named graph or triple added to graph URI

**Comment by k00ni** [comment]
> identified graphs will become 5 node, while true named graph are 4 node, I assume no as Its just a query translator, there's no way to differentiate between named graph or triple added to graph URI

What do you mean by "become 5 node"? In ARC2 knows only graphs, regardless if named or not in the first place. They are not added as triples, if that is what you meant. 

If you are not using SPARQL, how would like to "query" the data? Maybe you want something like [this](https://github.com/k00ni/knorke/tree/master/src/Knorke#resourceguy-and-resourceguyhelper) or [that](https://github.com/k00ni/knorke/blob/master/tests/Knorke/ResourceGuyHelperTest.php#L54)?

**Comment by johnss** [comment]
I already know that arc2 store it several different table, the values of triple stored it in id2val,s2val,o2val, a triples table that link that 3 table together, I don't know what exactly G2T table is used for but I think its used for nesting triple.

Example for 5 node is

Book1 (subject) -> title (predicate) -> example book title (object) 
And triple that link to book1 as object 
BookStore (subject) -> Have (predicate) -> [Book1 (subject) -> title (predicate) -> example book title (object)]

A true named graph doesn't need the predicate relation and will look like this
BookStore (context) ->  [Book1 (subject) -> title (predicate) -> example book title (object)]

The ResourceGuy & Helper and the unit test look the same to me, can you explain the differences?

**Comment by k00ni** [comment]
@johnss: ResourceGuy basically represents a sub graph, starting by a certain resource. You can access nodes and edges via array-access, like:

```php
$guy = new ResourceGuy();
$anotherGuy = new ResourceGuy();

// storing
$guy['foaf:name'] = $nodeFactory->createLiteral('Mister X');
$guy['foaf:knows'] = $anotherGuy; // ResourceGuy
$guy['foaf:name'] = 'Mister X'; // <== will result in an error, use instance of Literal instead

// getting
$guy['foaf:name'] = $nodeFactory->createLiteral('Mister X');
echo $guy['foaf:name'];
echo $guy['http://xmlns.com/foaf/0.1/name']; // <== will also work because of a known prefix foaf

// set and get URI of the ResourceGuy instance
$guy['_idUri'] = $nodeFactory->createNamedNode('http://uri/');
echo $guy['_idUri']->getUri(); // will output a string
```

ResourceGuyHelper makes it easier to get/create these subgraphs. For instance get all resources of a certain RDF type.

**Comment by k00ni** [comment]
Can this issue be closed?

**Comment by johnss** [comment]
What i want to achieve is to create a site similar to now defunct FreeBase or WikiData.org but only admin can create/edit without user registration, initialy i want to create it from scratch using ARC2.
Initialy think SQLstore of ARC2 can do but after some performance testing for quite large dataset seems not fine as it seems using EAV, also named graph support is unknown.
Named Graph is important because i want to filter the items only related to the context (graph name) and display as table.
After that i found and using laravelvoyager.com an Admin Panel only CMS the downside is i need to edit the frontend code for every table i want to display, so for 10 table i need 10 front end code, probably its possible to code it using single code for all table but i dont know how to code it.
After some research googling about how to create, retrieve from DB and display table using single code in PHP i come across Drupal 8, i did not know that Drupal can achieve this complex tasks without requiring to write single line of code.
https://www.ostraining.com/blog/drupal/entity-reference-views/
It is called Entity Reference, a Views called Favorite Animals i think can be equivalent to named graph, Views "Favorite Animal" will displays a table with 3 column People, Favorite animal and Animal Image
the link is tutorial for Drupal 7 but for Drupal 8 need very small minor change, for example there is no "Entity Reference: Referenced Entity"  is now changed to "Content Referenced From" in Drupal 8.

Maybe this story better to be placed in blogs or similar, but i do not have & and do not want to create blogs, I hope this comment will help everyone who read this comment be possible to create sites like i want as above mentioned, a knowledge base website consists of highly structured and linked data.
