### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by saphiree** [semsol/arc2#104]
Hai, I want to ask you, when I querying in SPARQL, I've got this error because maximum execution time of 30 seconds exceeded. How to fix it? So, I still didn't get the result of the query because of that
Thank you :)

This is the error what I've got 
![max eror](https://user-images.githubusercontent.com/26443406/39283415-592bc6b2-4938-11e8-8f49-21208ce06127.PNG)

**Comment by k00ni** [comment]
Hi @saphiree, can you please paste your SPARQL query and the code "around" it?

**Comment by saphiree** [comment]
I try to change setting inside xampp, and it solved that problem, so I don't get that error again .. :)
Maybe because arc2 make temporary db in sql, so I must change few things in xampp .. But thank you @k00ni for your reply :)

**Comment by k00ni** [comment]
Can this be closed?

**Comment by saphiree** [comment]
Yes ^^, sorry for the late response

**Comment by k00ni** [comment]
No problem.
