### ISSUE TITLE
Fatal error: Class 'ARC2\Store\Adapter\AbstractAdapter' not found

### ISSUE THREAD

**Issue by silviolorusso** [semsol/arc2#129]
Hi, I'm trying to use an updated version of ARC2 but I get the following error:

`Fatal error: Class 'ARC2\Store\Adapter\AbstractAdapter' not found in /[...]/ARC2/Store/Adapter/mysqliAdapter.php on line 17`

Any suggestion?

**Comment by k00ni** [comment]
Hi, did you ran `composer update` without any errors? And how do you include ARC2, via `vendor/autoload.php`?

**Comment by silviolorusso** [comment]
As I am not familiar with composer, I just copy pasted the full repo, including ARC2 as follows:

`require 'lib/arc2/ARC2.php';`

**Comment by k00ni** [comment]
Composer helps you to install PHP scripts and libraries. You can run it in the terminal very easily. Here is an [introduction](https://getcomposer.org/doc/00-intro.md).

If you don't want or can use it, the only way is to manually include ALL required PHP files by yourself. In your case, for instance:
* src/ARC2/Store/Adapter/mysqliAdapter.php
* src/ARC2/Store/Adapter/AbstractAdapter.php

and so on. Hope it helps.

**Comment by silviolorusso** [comment]
Thanks. The installation worked fine!
