### ISSUE TITLE
SPARQL + Endpoint

### ISSUE THREAD

**Issue by 1ats** [semsol/arc2#150]
Dear,

I did the following setup (https://github.com/semsol/arc2/wiki/SPARQL-Endpoint-Setup). The database connection is working correctly. Takes me to a screen (ARC SPARQL+ Endpoint (v2011-12-01)). But I have some doubts:

1- How do I create a sparql endpoint on this screen?
2- Maybe not necessary, but in which part of this configuration (https://github.com/semsol/arc2/wiki/SPARQL-Endpoint-Setup) do I add my ttl, OWL/XML, rdf file?

Grateful.

**Comment by k00ni** [comment]
**Regarding 1**: I never did setup a SPARQL endpoint myself, but as far as I understand it, there is no user interface. Your program directly communicates with the URL. So if your setup is accessible via for instance: `http://localhost/test.php`, that means one can use this URL to query your ARC2-based store.

**Regarding 2**: It seems there is no way to add a file so it is served by the SPARQL endpoint. You have to import these files beforehand (manually) into the ARC2 store.

**Comment by k00ni** [comment]
Closed due to inactivity.
