### ISSUE TITLE
JSON Serializer and end-quote

### ISSUE THREAD

**Issue by dennistobar** [semsol/arc2#20]
Hi everyone:

Today I installed ARC2, from git source, in a small server and load into it around 200K triples. So I've tested the recommended endpoint, as appears in the wiki page.

But JSON serializer has some problem: I've a parsing error with end quote of some strings. I checked it and it's true: some string are like this:

 "title": {
          "type": "literal",
          "value": "The new wave \"A book of the test\"
        },

And the parser won't like this string :(.

I hace implemened the solution in the issue #10, but the problem still exists. Any idea?

Thanks in advance

**Comment by craigdietrich** [comment]
I believe this was resolved a number of years ago.  See https://github.com/semsol/arc2/issues/10  @semsol
