### ISSUE TITLE
Table does not unlock after delete

### ISSUE THREAD

**Issue by johanneshahn** [semsol/arc2#33]
Hi,
i get some DB errors (Could not get lock in "runQuery" ...) when i delete a triple and after that insert a new one.
Think theres a missing release/unlock Table after delete.
In class ARC2_StoreDeleteQueryHandler function cleanValueTables().

Ill add $this->store->releaseLock(); at the end of function near line 229.

Error is gone.

**Comment by craigdietrich** [comment]
This seems easy enough -- I'll make the change and run a pull request.

Though, curious if there is a reason that the line 229 is commented out:
//mysql_query($sql, $con);
https://github.com/semsol/arc2/blob/master/store/ARC2_StoreDeleteQueryHandler.php

This goes pretty far back, so I'm guessing @bnowack had a reason?

**Comment by samuell** [comment]
@craigdietrich Was there a pull request for this? (Interested in an unambiguous fix for the problem :) )

**Comment by samuell** [comment]
Ok, so I tried to apply this myself. Seems to work great.

For future ref: I generated a patch from the original file with `.orig` added before `.php`, and the newly changed file like so:

```bash
[samuel arc2]$ diff -p store/ARC2_StoreDeleteQueryHandler{.orig,}.php
```
Resulting in this patch:
```patch
*** store/ARC2_StoreDeleteQueryHandler.orig.php Wed Jun 29 15:20:18 2016
--- store/ARC2_StoreDeleteQueryHandler.php      Wed Jun 29 15:19:17 2016
*************** class ARC2_StoreDeleteQueryHandler exten
*** 226,231 ****
--- 226,233 ----
        WHERE G.g IS NULL AND T1.t IS NULL AND T2.t IS NULL
      ';
      //mysql_query($sql, $con);
+     /* release lock */
+     $this->store->releaseLock();
    }
    
    /*  */
```

**Comment by bnowack** [comment]
Thanks guys!

**Comment by craigdietrich** [comment]
Thanks all!

**Comment by jvieille** [comment]
This foinally solved a decade long issue on Drupal File Framework!
Thanks
