### ISSUE TITLE
More documentation!

### ISSUE THREAD

**Issue by polkovnikov-ph** [semsol/arc2#44]
There's a plenty of real world use cases, which are not covered by documentation at all.
1) How could I insert a triple?
2) How could I insert a triple array (w/o SPARQL/U1)?
3) How could I use the library to deal with gigabytes of data?

**Comment by k00ni** [comment]
To answer some of your questions:

> 1) How could i insert a triple?

See that section in the wiki: https://github.com/semsol/arc2/wiki/SPARQL-#insert-example

> 2) How could I insert a triple array (w/o SPARQL/U1)?

I had to dealt with that question recently. Our stack provided the triples in form of an statement list, so i transform each statement into its n-quad representation and add it to the SPARQL query. At the end i have an SPARQL query such as:

```
INSERT INTO <http://example.com/> {
 <#foo> <bar> "baz" . 
 <#foo22> <bar> "baz" . 
 <#foo333> <bar> "baz" . 
}
```

whereas each line between the braces represents one statement of my statement list. Hope that information helps! For more information how we do that, have a look [here](https://github.com/SaftIng/Saft/blob/master/src/Saft/Backend/ARC2/Store/ARC2.php#L78).

**Comment by polkovnikov-ph** [comment]
@k00ni "w/o" is a short form of "without". An amount of serialization/deserialization required and an amount of ways to spawn bugs are a total nonsense for such a simple task.

**Comment by polkovnikov-ph** [comment]
Does it take three years to answer?

**Comment by olberger** [comment]
Probably when the project is more or less unmaintained, or when documentation isn't the priority... now, complaining won't help much : either you solved the issues during that time, or you're really not in a hurry, aren't you ? ;-)

What about contributing some docs, if you've more or less managed to workaround/solve the issue ?

Hope this helps (I'm no maintainer, in case of doubt).

**Comment by polkovnikov-ph** [comment]
Wait, what? Was it fixed?

**Comment by akuckartz** [comment]
How was this resolved?
