### ISSUE TITLE
Traversing a subgraph

### ISSUE THREAD

**Issue by redskate** [semsol/arc2#45]
Hello everybody

I need to traverse a subgraph in my ARC2 RDF store, some SPARQL engines like virtuoso use transitive closures to get all data inside a subgraph starting from a given node. I would like to do the same with ARC, starting from a node (a subject) inside an RDF graph in the ARC triple store and getting all the outgoing triples from that node on in the store. 

Is there an elegant solution without using SPARQLSCRIPT?
Thank you very much in advance for any suggestion / answer

Cheers

**Comment by k00ni** [comment]
Hi @redskate, could you find a solution for your problem?

**Comment by redskate** [comment]
Thank you very much for asking. Well after 5 years I did found one :)

**Comment by k00ni** [comment]
Sorry for the late answer. I just wanted to see, if there is anything we can do, even after 5 years :) Glad you found it.
