### ISSUE TITLE
Please document the test suite

### ISSUE THREAD

**Issue by olberger** [semsol/arc2#48]
I believe it might be useful for some to know about the test suite.

AFAICT, ant + phpunit is needed.

Maybe a wiki page could help ?

Thanks in advance.

**Comment by k00ni** [comment]
Hi @olberger, despite this post is very old: i updated the test environment recently and added the file `doc/developer.md`. It contains basic information for people interested in having a deeper look into ARC2 internals. Currently it rests in branch `2.4` but will be merged into master soon.

I will close this for now, feel free to comment again, if necessary.
