### ISSUE TITLE
DROP graph not supported?

### ISSUE THREAD

**Issue by coreation** [semsol/arc2#62]
I currently inject triples into named graphs, which works just fine. However I seem to run into problems when I perform a "DROP GRAPH <name_of_the_graph>" query. Is this type of query supported out of the box (I don't see the drop statement in the store documentation), and if not supported is there a way to manage these named graphs, because if you can't delete them, it seems like a small mem-leak to me?

Thanks in advance.

**Comment by k00ni** [comment]
I ran into the same problem as @coreation: removing the graph via 

```
DELETE FROM <http://foobar/>
```

left the triples untouched. Is this intentional or a bug?

**Comment by coreation** [comment]
I think this repository is not maintained anymore, only PR's are accepted from time to time I'm afraid.

**Comment by k00ni** [comment]
I implemented a [*solution*](https://github.com/SaftIng/Saft/blob/master/src/Saft/Addition/ARC2/Store/ARC2.php#L250) in our RDF framework called Saft, which makes use of ARC2 as backend. If this is a bug, i could try to fix it in ARC2 directly.

**Comment by bnowack** [comment]
Hi,
keeping the term hashes was intentional, so that ARC re-uses internal IDs after their first creation. IIRC, this had a speed benefit when a store frequently gets cleared and re-populated.

For clean DB tables, I used to do a SPOG export + import in a fresh store.

**Comment by k00ni** [comment]
> For clean DB tables, I used to do a SPOG export + import in a fresh store.

Would you explain that further, please? How can i clean the tables when dropping a graph?

**Comment by bnowack** [comment]
Basically, you can't clean the tables through SPARQL+.

There is a `$store->createBackup` method, which lets you write a backup file to disk (or alternatively the SPARQL+ query `DUMP` which returns the backup data).

Then you can reset the store (`$store->reset()`) and re-import the backup file via a `LOAD <path/to/backup-file.spog>` query. (If I remember correctly, haven't looked at the code for quite some time...)

The 2nd step ($store->reset()) cannot be done via the endpoint at the moment, and it is not graph-specific but clears all tables. In all other cases, keeping the term hashes is/was intentionally, although I don't fully remember the reasons  ;-)
