### ISSUE TITLE
credentials for sesame remote_store_endpoint?

### ISSUE THREAD

**Issue by kgeographer** [semsol/arc2#64]
I have a Sesame 2.7.11 store I can access fine with Workbench and the Win2 client. The Win2 client respects permissions set in web.xml, so I can secure it. Can't run queries with arc2 though if any security is set. arc2 does work if I leave the store wide open.

How can I send BASIC authentication credentials? I see in ARC2_Reader.php an arc_reader_credentials array() and tried un-commenting and supplying a 'host' => 'user:pass' for the endpoint but I get 500 errors in the browser. Tried hard and failed to  locate any other documentation.

any suggestions appreciated, thanks

**Comment by k00ni** [comment]
Hi @kgeographer, any news here? Issue seems solved to me.
