### ISSUE TITLE
Remote endpoint problem

### ISSUE THREAD

**Issue by moissinac** [semsol/arc2#66]
When I do request from my development machine to my remote endpoint, all is OK
When I do the same request from deployed server to my remote endpoint, I get the following message
Query errorsArray ( [0] => Socket error: Could not connect to "http://137.194.54.188:8890/sparql?query=%0A%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aselect+distinct+%3Fp+%3Fo+where+%7B%0AGRAPH+%3Chttp%3A%2F%2Fgivingsense.eu%2Ffrscol%2FFrSchoolSystem%2F%3E+%7B%0A%3Chttp%3A%2F%2Fgivingsense.eu%2Ffrscol%2FFrSchoolSystem%2FPeriod1%3E+%3Fp+%3Fo+.%0A%7D%0A%7D%0A++" (proxy: 0): Connexion terminée par expiration du délai d'attente in ARC2_Reader [1] => missing stream in "getFormat" via ARC2_Reader [2] => missing stream in "readStream" http://137.194.54.188:8890/sparql?query=%0A%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aselect+distinct+%3Fp+%3Fo+where+%7B%0AGRAPH+%3Chttp%3A%2F%2Fgivingsense.eu%2Ffrscol%2FFrSchoolSystem%2F%3E+%7B%0A%3Chttp%3A%2F%2Fgivingsense.eu%2Ffrscol%2FFrSchoolSystem%2FPeriod1%3E+%3Fp+%3Fo+.%0A%7D%0A%7D%0A++ via ARC2_Reader )

If I copy/paste in a browser the request included in the message, it works:
http://137.194.54.188:8890/sparql?query=%0A%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aselect+distinct+%3Fp+%3Fo+where+%7B%0AGRAPH+%3Chttp%3A%2F%2Fgivingsense.eu%2Ffrscol%2FFrSchoolSystem%2F%3E+%7B%0A%3Chttp%3A%2F%2Fgivingsense.eu%2Ffrscol%2FFrSchoolSystem%2FPeriod1%3E+%3Fp+%3Fo+.%0A%7D%0A%7D%0A++

I'm working on that issue from a while without finding my way
Help will be appreciated

**Comment by Habennin** [comment]
I am experiencing this problem in 2018. Did anybody encounter and or fix it in the meantime? 

If so your advice would be greatly appreciated. I am normally able to call remote endpoints using ARC2.

I run the script on my external host. It works fine for many known endpoints. It seems not to work fine for the endpoint I have at work which ends in 8090. Is the port an issue perhaps?

**Comment by k00ni** [comment]
A first wild guess is, that the deployed server has some kind of a blacklist of ports active. Can you check that?

Do you have shell access to the deployed server? If so, can you ping the remote endpoint using curl, for instance?

**Comment by k00ni** [comment]
Any news here?

**Comment by k00ni** [comment]
Close because no feedback.
