### ISSUE TITLE
Does ARC2 supports reading and writing to default graph?

### ISSUE THREAD

**Issue by k00ni** [semsol/arc2#72]
I am trying to find out how ARC2 supports default graph operations. Writing to default graphs seems to work:

> INSERT DATA { http://example.org/a http://example.org/b http://example.org/c }

But afterwards the tables are still empty, nothing was inserted. 

Same goes for the following SPARQL SELECT query:

> SELECT \* { http://example.org/a ?p ?o }

It gets passed, but returns nothing.

Any ideas?

**Comment by k00ni** [comment]
*ping* :)

**Comment by k00ni** [comment]
ping again :)

**Comment by bnowack** [comment]
Can't remember if ARC2 supports a default graph, to be honest. I *think* you always have to specify an "INTO".

**Comment by k00ni** [comment]
Ok, thanks.
