### ISSUE TITLE
Add support for serializing to JSON-LD

### ISSUE THREAD

**Issue by jaw111** [semsol/arc2#73]
As JSON-LD is standardized for a while, would be nice to support it as a serialization format

**Comment by craigdietrich** [comment]
I'd really like to see this happen.  EasyRDF's JSON-LD serializer (https://github.com/njh/easyrdf/blob/master/lib/Serialiser/JsonLd.php) could probably be used as a guide to creating an ARC2 serializer.  (EasyRDF has an ARC2 extractor, but this seems like hitting a tack with a hammer to have both operating on the same application.)

**Comment by jaw111** [comment]
Created PR #79 that implements JSON-LD serializer
