### ISSUE TITLE
SPARQL CONSTRUCT IN ARC

### ISSUE THREAD

**Issue by mohamedragab** [semsol/arc2#75]
how can i use Construct queries   with ARC

**Comment by k00ni** [comment]
I found the following Wiki-pages concerning Construct queries:
- https://github.com/semsol/arc2/wiki/Using-ARC's-RDF-Store (scroll to the middle)
- https://github.com/semsol/arc2/wiki/SPARQL%2B

Hope it helps.

**Comment by k00ni** [comment]
Can this be closed?

**Comment by k00ni** [comment]
Closed because no feedback.
