### ISSUE TITLE
how to parsing value of query from one page to another page ?

### ISSUE THREAD

**Issue by saphiree** [semsol/arc2#82]
I'm sorry, I'm a beginner in sparql, and now I'm working on ontologies project.
I have a query result in a.php then I want to use that query result to b.php, is it possible ? 
How to parsing it ?
I've tried using $_POST and $_GET (because when I've tried $_POST in same page, it's working), but still not working 
This is code to show query result in a.php
![012](https://cloud.githubusercontent.com/assets/26443406/25913198/121ae70c-35e4-11e7-91bf-1028a194efde.PNG)
And this is query from b.php
I want to make the query result from a.php ($row['resep']) into filter in b.php
![013](https://cloud.githubusercontent.com/assets/26443406/25913237/3c9e55cc-35e4-11e7-8611-aa24d8e5a2f1.PNG)

 Thank you,

**Comment by k00ni** [comment]
Hi, can you please paste relevant code inside a codeblock ([link](https://help.github.com/articles/creating-and-highlighting-code-blocks/)). How do you send the query? What do you want to do with the result? As i can see, you want to output the result inside a table, but the regex-HTML-mix is very confusing, sorry.

**Comment by saphiree** [comment]
This is query from the a.php which is the result show food recipe (based on age) inside tabel with 2 actions, see recipe and choose recipe with link

`//$_POST['s'] = certain age that chosen by user
<?php
if (isset($_POST['s'])) 
          {
             $q ='
                PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                PREFIX owl: <http://www.w3.org/2002/07/owl#>
                PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
                PREFIX mpasi: <http://www.semanticweb.org/astrid/ontologies/mpasi#>
                SELECT DISTINCT ?food
                WHERE {
                ?food mpasi:resepFor ?babyAge.
                ?malnutrition mpasi:hasTreatment ?food.
                FILTER regex (str(?babyAge),"'.$_POST['s'].'").
                }
                ORDER By ?food'; 
        ?>

              <div align="center">
              <?php
              $r = '';
              $id = 0;
                if ($rows = $store->query($q, 'rows')) {
              /* display the results in an HTML table */
                  echo "<table border='1'>
                  <thead>
                      <th>No</th>
                      <th>Recipe</th>
                      <th>Action</th>
                  </thead>";
              /* loop for each returned row */
              ?>
              <?php
              foreach( $rows as $row ) { 
                print "<tr><td>".++$id. "</td>
                  <td>" .$row['food']. "</td>
                 <td>" ?><a href='see_recipe.php?food="<?php echo $row['food'];?>"'>See | <a href='choose_recipe.php?food="<?php echo $row['food'];?>"'>Choose</a><?php "</td>";
}
}
}
`              
Yes, sorry .. I fix it little (regex-HTML section)
In that action column, I want to parsing the value of $row['food'] which is contain certain food that chosen by user to see_recipe.php and choose_recipe.php 
But I don't know how to parsing that value to another page
In see_recipe.php I want to query again with that value to view the detail, and in choose_recipe.php I want to query again and save the query result in dbase mysql and process it with method

Thank you

**Comment by k00ni** [comment]
No feedback since 3 years, therefore closed.
