### ISSUE TITLE
Please activate Travis for this repository

### ISSUE THREAD

**Issue by k00ni** [semsol/arc2#87]
With a past pull request, we got Travis support, but we still need to set Travis up in the settings. Please do the following steps: 

1. Login into [Travis](https://travis-ci.org/) using your Github account.
2. In the Travis profile (for instance, mine would be https://travis-ci.org/profile/k00ni), click on the eye-symbol next to your image. Copy that token.
3. Please add Travis as service [here](https://github.com/semsol/arc2/settings/installations). 
    * use the copied token
    * use notify.travis-ci.org for the Domain field.

That's it. With that change, not only ARC2 will be tested but also future pull requests.

**Comment by semsol** [comment]
Done.

**Comment by k00ni** [comment]
Can you add the Travis link for ARC2 here? I would like to add the Travis badge to the README.md.

**Comment by k00ni** [comment]
Great!
