### ISSUE TITLE
arc2 in python or similar

### ISSUE THREAD

**Issue by jesushd12** [semsol/arc2#89]
Hi, is there an implementation of arc2 in Python? 
If not, Do you know What others library has similar functionalities in Python? I've tried rdflib but I couldn't store triplestore and I had some problems with it, also I haven't see projects using it.

**Comment by k00ni** [comment]
I have no knowledge about an ARC2 implementation in Python. RDFlib seems a good tool, i know people using it very successfully. 

Can this be closed?

**Comment by jesushd12** [comment]
Hi @k00ni thanks for your answer. Yes.
