### ISSUE TITLE
Problem with count and distinct

### ISSUE THREAD

**Issue by moissinac** [semsol/arc2#92]
I'm trying the following request

```sparql
select (count(distinct ?serie) as ?c) where {
graph <http://givingsense.eu/onto/sembib/channels> { 
?s <http://givingsense.eu/onto/sembib/inConf> ?o .
?o ?p ?serie
}
}
```
and I get
No result bindings specified. in ARC2_SPARQLPlusParser

I see nothing in the doc which say that such construct in unsupported.
Am I wrong?

**EDIT by @k00ni:** added syntax highlighting to query.

**Comment by johanneshahn** [comment]
Sehr geehrte Damen und Herren,

bitte beachten Sie, dass ich bis 04.09.2017 nicht zu erreichen bin. Ihre Anfrage wird nach meiner Rückkehr schnellstmöglich bearbeitet.  Vielen Dank.

*********************************************************************************************************************************************************************************************

Thank you for your email.

I will be out of the office until 04.09.2017. Your email will not be forwarded but I will deal with it on my return.

Johannes Hahn
Geschäftsführer - Mediadevelopment
---------------------------------------------------------------------------------------------------------------------

eccence 
Weimarstrasse 1 • D-70176 Stuttgart

fon	 +49(0)711.4 77 88 77 9

email j.hahn@eccence.de  
web www.eccence.de

Geschäftsführer: Gerd Freiwald & Johannes Hahn
Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: DE259976593

**Comment by k00ni** [comment]
Hi @moissinac, here is a COUNT example: https://github.com/semsol/arc2/wiki/SPARQL-#aggregate-example

Also using GRAPH in your WHERE clause is not supported by ARC2. Its also required when using URIs to have `<` and `>` around.

This query may get the job done:

```sparql
SELECT count(?serie) as ?c
FROM <http://givingsense.eu/onto/sembib/channels>
WHERE {
    ?s <http://givingsense.eu/onto/sembib/inConf> ?o .
    ?o ?p ?serie
}
GROUP BY ?serie
```

**Comment by k00ni** [comment]
Closed, because no response. Please reopen, if problem persists.
