### ISSUE TITLE
Does ARC2 have an in-memory store?

### ISSUE THREAD

**Issue by k00ni** [semsol/arc2#95]
File [store/ARC2_MemStore.php](https://github.com/semsol/arc2/blob/master/store/ARC2_MemStore.php) looks promising. Can anybody tell me, if its a full in memory store?

**Comment by k00ni** [comment]
@semsol: Ping :)

If there isn't one, how hard would it be to port the actual one?

**Comment by bnowack** [comment]
That class looks more like a copy of the RemoteEndpoint. For an in-memory parser we would need in-memory query processing, which does not exist in ARC2. Pattern evaluation is only translated to SQL at the moment.

**Comment by k00ni** [comment]
Okay, can be closed due question answered :)
